### ISSUE TITLE
中文网页会乱码，不止GBK编码，包括UTF-8

### ISSUE THREAD

**Issue by cyhuajuan** [amio/pageshot#3]
比如百度，以及我自己的博客

**Comment by amio** [comment]
目前的 shot.now.sh 是基于这个 [Dockerfile](https://github.com/amio/docker-node-chrome/blob/master/Dockerfile) 部署的，估计原因应该是原始镜像里缺少中文字体。尝试加了 fonts-noto-cjk 有点问题，晚些搞

**Comment by amio** [comment]
已修复。新 Dockerfile https://hub.docker.com/r/amio/node-chrome-cjk/
