### ISSUE TITLE
Problems with connection

### ISSUE THREAD

**Issue by lucianopf** [amio/pageshot#4]
When trying to take any shot it does throw this error. =/

```
 Error: connect ECONNREFUSED 127.0.0.1:9222
      at Object.exports._errnoException (util.js:1022:11)
      at exports._exceptionWithHostPort (util.js:1045:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
```

**Comment by amio** [comment]
The headless-chrome seems encountered some problem

It should works now. Thanks for reporting!

**Comment by amio** [comment]
Considering use the fresh [puppeteer](https://github.com/GoogleChrome/puppeteer) instead of chrome-remote-interface later

**Comment by amio** [comment]
Replaced CDP with puppeteer in ff18665259396e628729a88d15cf2d875fa82138
